# Generated by Django 5.0.2 on 2024-02-13 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Custamer_Name', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Mobile_Number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_Id', models.IntegerField(primary_key=True, serialize=False)),
                ('Delivary_Type', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Payment_Status', models.CharField(max_length=100)),
                ('Custamer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.login')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Custamer_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Of_Orders', models.IntegerField()),
                ('Total_Amount', models.IntegerField()),
                ('City', models.CharField(max_length=100)),
                ('Adress', models.TextField()),
                ('Last_Order', models.DateField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.profile')),
                ('Email', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.login')),
                ('Custamer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_details', to='app1.orders')),
                ('Order_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.orders')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
                ('Category_Name', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Stack', models.IntegerField()),
                ('Out_Of_Stack', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='Product_Name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.products'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_Images', models.ImageField(upload_to='product_images/')),
                ('Product_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app1.products')),
            ],
        ),
        migrations.CreateModel(
            name='Add_TO_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Custamer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.custamer_details')),
                ('Product_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.products')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Custamer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.custamer_details')),
                ('Product_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.products')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
