# Generated by Django 5.0.2 on 2024-02-13 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_parent_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custamer_details',
            name='Custamer_Name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Adress',
        ),
    ]
