# Generated by Django 5.0.2 on 2024-02-14 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_products_description_rating_rating_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Children',
        ),
        migrations.DeleteModel(
            name='Parent',
        ),
    ]
