# Generated by Django 5.0.2 on 2024-02-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_delete_children_delete_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Full_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
