# Generated by Django 5.0.2 on 2024-02-14 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_orders_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
