# Generated by Django 5.0.2 on 2024-02-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_orders_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_Id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
