# Generated by Django 5.0.2 on 2024-02-14 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_custamer_details_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('Order_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Delivary_Type', models.CharField(max_length=100)),
                ('Payment_Status', models.CharField(max_length=100)),
                ('Full_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Custamer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.login')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Custamer_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('No_Of_Orders', models.IntegerField()),
                ('Total_Amount', models.IntegerField()),
                ('City', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('Adress', models.TextField()),
                ('Product_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.products')),
                ('Order_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.orders')),
            ],
        ),
    ]
