# Generated by Django 5.0.2 on 2024-02-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_orders_custamer_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Full_Name',
        ),
        migrations.AddField(
            model_name='custamer_details',
            name='Full_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
