# Generated by Django 5.0.2 on 2024-02-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_orders_full_name_custamer_details_full_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Custamer_Name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='username',
        ),
        migrations.DeleteModel(
            name='Custamer_Details',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
