# Generated by Django 5.0.2 on 2024-02-14 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_custamer_details_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='Product_Name',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='username',
        ),
        migrations.DeleteModel(
            name='Custamer_Details',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
