# Generated by Django 5.0.2 on 2024-02-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_image_imageurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='custamer_details',
            name='Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
