# Generated by Django 5.0.2 on 2024-02-18 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_custamer_details_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
