# Generated by Django 5.0.2 on 2024-02-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_login_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_TO_Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Custamer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.custamer_details')),
                ('Product_Name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.products')),
            ],
        ),
    ]
