# Generated by Django 5.0.2 on 2024-02-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_custamer_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custamer_details',
            name='Quantity',
            field=models.IntegerField(),
        ),
    ]
