# Generated by Django 5.0.2 on 2024-02-22 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_alter_custamer_details_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='P_Url',
            field=models.TextField(default='Not Sucess'),
        ),
    ]
