# Generated by Django 5.0.2 on 2024-02-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0029_profile_p_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='Discount',
            field=models.IntegerField(default=30),
        ),
    ]
