# Generated by Django 5.0.2 on 2024-02-23 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_imagessss'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CupenCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code_Name', models.CharField(max_length=10)),
                ('Code_Off', models.IntegerField()),
                ('Limit', models.IntegerField()),
                ('Custamer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.login')),
                ('Product_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.products')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Imagessss',
        ),
    ]
