# Generated by Django 5.0.2 on 2024-02-23 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_cupencode_delete_imagessss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CupenCode',
        ),
    ]
