# Generated by Django 5.0.2 on 2024-02-23 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_alter_products_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CupenCode',
        ),
    ]
