# Generated by Django 5.0.2 on 2024-02-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_cupencode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cupencode',
            name='HowMany_Days',
        ),
    ]
