# Generated by Django 5.0.2 on 2024-02-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_remove_cupencode_howmany_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupencode',
            name='Code_Name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
