# Generated by Django 5.0.2 on 2024-02-23 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_alter_cupencode_code_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Times', models.IntegerField()),
                ('Code_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.cupencode')),
            ],
        ),
    ]
