# Generated by Django 5.0.2 on 2024-03-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_orders_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='ImageUrl',
            field=models.URLField(null=True),
        ),
    ]
