# Generated by Django 5.0.2 on 2024-03-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_alter_orders_imageurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='ImageUrl',
        ),
    ]
