# Generated by Django 5.0.2 on 2024-03-10 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_remove_orders_imageurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.custamer_details')),
                ('Custamer_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.login')),
                ('Order_Id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.orders')),
            ],
        ),
    ]
