# Generated by Django 5.0.2 on 2024-03-10 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adress',
            old_name='Adress',
            new_name='Adresss',
        ),
    ]
